// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/saikewei/my_website/back/internal/model"
)

func newPhotoTag(db *gorm.DB, opts ...gen.DOOption) photoTag {
	_photoTag := photoTag{}

	_photoTag.photoTagDo.UseDB(db, opts...)
	_photoTag.photoTagDo.UseModel(&model.PhotoTag{})

	tableName := _photoTag.photoTagDo.TableName()
	_photoTag.ALL = field.NewAsterisk(tableName)
	_photoTag.PhotoID = field.NewInt32(tableName, "photo_id")
	_photoTag.TagID = field.NewInt32(tableName, "tag_id")

	_photoTag.fillFieldMap()

	return _photoTag
}

type photoTag struct {
	photoTagDo

	ALL     field.Asterisk
	PhotoID field.Int32
	TagID   field.Int32

	fieldMap map[string]field.Expr
}

func (p photoTag) Table(newTableName string) *photoTag {
	p.photoTagDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p photoTag) As(alias string) *photoTag {
	p.photoTagDo.DO = *(p.photoTagDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *photoTag) updateTableName(table string) *photoTag {
	p.ALL = field.NewAsterisk(table)
	p.PhotoID = field.NewInt32(table, "photo_id")
	p.TagID = field.NewInt32(table, "tag_id")

	p.fillFieldMap()

	return p
}

func (p *photoTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *photoTag) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["photo_id"] = p.PhotoID
	p.fieldMap["tag_id"] = p.TagID
}

func (p photoTag) clone(db *gorm.DB) photoTag {
	p.photoTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p photoTag) replaceDB(db *gorm.DB) photoTag {
	p.photoTagDo.ReplaceDB(db)
	return p
}

type photoTagDo struct{ gen.DO }

func (p photoTagDo) Debug() *photoTagDo {
	return p.withDO(p.DO.Debug())
}

func (p photoTagDo) WithContext(ctx context.Context) *photoTagDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p photoTagDo) ReadDB() *photoTagDo {
	return p.Clauses(dbresolver.Read)
}

func (p photoTagDo) WriteDB() *photoTagDo {
	return p.Clauses(dbresolver.Write)
}

func (p photoTagDo) Session(config *gorm.Session) *photoTagDo {
	return p.withDO(p.DO.Session(config))
}

func (p photoTagDo) Clauses(conds ...clause.Expression) *photoTagDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p photoTagDo) Returning(value interface{}, columns ...string) *photoTagDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p photoTagDo) Not(conds ...gen.Condition) *photoTagDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p photoTagDo) Or(conds ...gen.Condition) *photoTagDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p photoTagDo) Select(conds ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p photoTagDo) Where(conds ...gen.Condition) *photoTagDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p photoTagDo) Order(conds ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p photoTagDo) Distinct(cols ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p photoTagDo) Omit(cols ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p photoTagDo) Join(table schema.Tabler, on ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p photoTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p photoTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p photoTagDo) Group(cols ...field.Expr) *photoTagDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p photoTagDo) Having(conds ...gen.Condition) *photoTagDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p photoTagDo) Limit(limit int) *photoTagDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p photoTagDo) Offset(offset int) *photoTagDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p photoTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *photoTagDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p photoTagDo) Unscoped() *photoTagDo {
	return p.withDO(p.DO.Unscoped())
}

func (p photoTagDo) Create(values ...*model.PhotoTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p photoTagDo) CreateInBatches(values []*model.PhotoTag, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p photoTagDo) Save(values ...*model.PhotoTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p photoTagDo) First() (*model.PhotoTag, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Take() (*model.PhotoTag, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Last() (*model.PhotoTag, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Find() ([]*model.PhotoTag, error) {
	result, err := p.DO.Find()
	return result.([]*model.PhotoTag), err
}

func (p photoTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PhotoTag, err error) {
	buf := make([]*model.PhotoTag, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p photoTagDo) FindInBatches(result *[]*model.PhotoTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p photoTagDo) Attrs(attrs ...field.AssignExpr) *photoTagDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p photoTagDo) Assign(attrs ...field.AssignExpr) *photoTagDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p photoTagDo) Joins(fields ...field.RelationField) *photoTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p photoTagDo) Preload(fields ...field.RelationField) *photoTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p photoTagDo) FirstOrInit() (*model.PhotoTag, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) FirstOrCreate() (*model.PhotoTag, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) FindByPage(offset int, limit int) (result []*model.PhotoTag, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p photoTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p photoTagDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p photoTagDo) Delete(models ...*model.PhotoTag) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *photoTagDo) withDO(do gen.Dao) *photoTagDo {
	p.DO = *do.(*gen.DO)
	return p
}
