// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePhoto = "photos"

// Photo mapped from table <photos>
type Photo struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AlbumID     int32     `gorm:"column:album_id;comment:所属相册ID, 关联albums.id (可以为空, 代表未分类)" json:"album_id"`                       // 所属相册ID, 关联albums.id (可以为空, 代表未分类)
	Title       string    `gorm:"column:title;not null;comment:照片标题" json:"title"`                                                 // 照片标题
	Description string    `gorm:"column:description;comment:照片描述或背后的故事" json:"description"`                                        // 照片描述或背后的故事
	FilePath    string    `gorm:"column:file_path;not null;comment:文件存储路径 (例如: /uploads/2024/09/your-photo.jpg)" json:"file_path"` // 文件存储路径 (例如: /uploads/2024/09/your-photo.jpg)
	FileName    string    `gorm:"column:file_name;not null;comment:原始文件名" json:"file_name"`                                        // 原始文件名
	FileSize    int32     `gorm:"column:file_size;not null;comment:文件大小 (Bytes)" json:"file_size"`                                 // 文件大小 (Bytes)
	Width       int32     `gorm:"column:width;not null;comment:图片宽度 (px)" json:"width"`                                            // 图片宽度 (px)
	Height      int32     `gorm:"column:height;not null;comment:图片高度 (px)" json:"height"`                                          // 图片高度 (px)
	IsFeatured  bool      `gorm:"column:is_featured;not null;comment:是否为精选照片" json:"is_featured"`                                  // 是否为精选照片
	ShotAt      time.Time `gorm:"column:shot_at;comment:拍摄时间" json:"shot_at"`                                                      // 拍摄时间
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Photo's table name
func (*Photo) TableName() string {
	return TableNamePhoto
}
