// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePhotoTag = "photo_tags"

// PhotoTag mapped from table <photo_tags>
type PhotoTag struct {
	PhotoID int32 `gorm:"column:photo_id;primaryKey" json:"photo_id"`
	TagID   int32 `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName PhotoTag's table name
func (*PhotoTag) TableName() string {
	return TableNamePhotoTag
}
