// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemPassword = "system_password"

// SystemPassword Stores the single system password
type SystemPassword struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PasswordHash string    `gorm:"column:password_hash;not null;comment:Hashed password using bcrypt" json:"password_hash"` // Hashed password using bcrypt
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SystemPassword's table name
func (*SystemPassword) TableName() string {
	return TableNameSystemPassword
}
