// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVPhotosWithDetail = "v_photos_with_details"

// VPhotosWithDetail VIEW
type VPhotosWithDetail struct {
	ID           int32      `gorm:"column:id;not null" json:"id"`
	AlbumID      *int32     `gorm:"column:album_id;comment:所属相册ID, 关联albums.id (可以为空, 代表未分类)" json:"album_id"`                       // 所属相册ID, 关联albums.id (可以为空, 代表未分类)
	Title        string     `gorm:"column:title;not null;comment:照片标题" json:"title"`                                                 // 照片标题
	Description  *string    `gorm:"column:description;comment:照片描述或背后的故事" json:"description"`                                        // 照片描述或背后的故事
	FilePath     string     `gorm:"column:file_path;not null;comment:文件存储路径 (例如: /uploads/2024/09/your-photo.jpg)" json:"file_path"` // 文件存储路径 (例如: /uploads/2024/09/your-photo.jpg)
	FileName     string     `gorm:"column:file_name;not null;comment:原始文件名" json:"file_name"`                                        // 原始文件名
	FileSize     int32      `gorm:"column:file_size;not null;comment:文件大小 (Bytes)" json:"file_size"`                                 // 文件大小 (Bytes)
	Width        int32      `gorm:"column:width;not null;comment:图片宽度 (px)" json:"width"`                                            // 图片宽度 (px)
	Height       int32      `gorm:"column:height;not null;comment:图片高度 (px)" json:"height"`                                          // 图片高度 (px)
	IsFeatured   bool       `gorm:"column:is_featured;not null;comment:是否为精选照片" json:"is_featured"`                                  // 是否为精选照片
	ShotAt       *time.Time `gorm:"column:shot_at;comment:拍摄时间" json:"shot_at"`                                                      // 拍摄时间
	CreatedAt    time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Camera       *string    `gorm:"column:camera;comment:相机" json:"camera"`                               // 相机
	Lens         *string    `gorm:"column:lens;comment:镜头" json:"lens"`                                   // 镜头
	FocalLength  *string    `gorm:"column:focal_length;comment:焦距 (例如: 85mm)" json:"focal_length"`        // 焦距 (例如: 85mm)
	Aperture     *string    `gorm:"column:aperture;comment:光圈 (例如: f/1.8)" json:"aperture"`               // 光圈 (例如: f/1.8)
	ShutterSpeed *string    `gorm:"column:shutter_speed;comment:快门速度 (例如: 1/1000s)" json:"shutter_speed"` // 快门速度 (例如: 1/1000s)
	Iso          *string    `gorm:"column:iso;comment:ISO感光度 (例如: 100)" json:"iso"`                       // ISO感光度 (例如: 100)
	ExposureBias *string    `gorm:"column:exposure_bias;comment:曝光补偿 (例如: +0.7 EV)" json:"exposure_bias"` // 曝光补偿 (例如: +0.7 EV)
	FlashFired   *bool      `gorm:"column:flash_fired;comment:是否使用闪光灯" json:"flash_fired"`                // 是否使用闪光灯
	GpsLatitude  *float64   `gorm:"column:gps_latitude;comment:GPS纬度" json:"gps_latitude"`                // GPS纬度
	GpsLongitude *float64   `gorm:"column:gps_longitude;comment:GPS经度" json:"gps_longitude"`              // GPS经度
	Tags         *string    `gorm:"column:tags" json:"tags"`
}

// TableName VPhotosWithDetail's table name
func (*VPhotosWithDetail) TableName() string {
	return TableNameVPhotosWithDetail
}
